### ISSUE TITLE
Method not found exception

### ISSUE THREAD

**Issue by steve-haar** [ianrathbone/Canduits.Owin.Security.Dropbox#1]
I am using your project with MVC 5 and get the following exception when my web app starts up: Method not found: 'System.String Microsoft.Owin.IOwinRequest.get_Path()'.

I am able to use other OWIN providers successfully though.

**Comment by ianrathbone** [comment]
Hi sorry to hear this, which version of OWIN are you using?

**Comment by steve-haar** [comment]
Microsoft ASP.NET MVC version 5.1.1
Microsoft OWIN version 2.1.0
Canduits.Owin.Security.Dropbox version 0.1.2.5

**Comment by ianrathbone** [comment]
Hey Steve just to let you know I've not forgotten you and I am putting a new version together that also brings the library up to the latest OWIN version, may even have it online today if it tests well.

**Comment by ianrathbone** [comment]
To update on the issue however I do believe you're seeing the issue because you're using a newer version of the OWIN lib. However I do need to update the project to make use of the latest version.
